version: '3'

services:
  caddy:
    container_name: caddy
    image: abiosoft/caddy:no-stats
    restart: always
    volumes:
      - ./config/Caddyfile.proxy:/etc/Caddyfile
      - ./config:/etc/caddycerts
    environment:
      CADDYPATH: /etc/caddycerts
      ACME_AGREE: 'true'
    ports:
      - '80:80'
      - '443:443'
