name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:  
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Snyk
        uses: snyk/actions@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
        
  docker-push: 
    runs-on: ubuntu-latest
    needs: scan
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: tgwing/amongus:latest
    
  heroku-depploy: 
    runs-on: ubuntu-latest
    needs: docker-push
    steps: 
      - name: Checkout 
        uses: actions/checkout@v2
      - name: Heroku deploy 
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "amongus-heroku-01"
          heroku_email: "puahhuiying@gmail.com"
